"""A projection of the backlog, never a second author (RK39).

A README section and a site page repeat what the backlog says and drift the moment it
changes, because nothing re-derives them. This repository's own README claimed **8 of 36
tasks shipped** and listed `add`, `ship`, `pick` and `show` as "not yet built" while all
four were in the ledger — written by the same session that shipped them.

So the restatement is derived. Two properties make it a projection rather than a generator:

* **Idempotent.** The same `docs/` yields the same bytes, so a refresh with nothing to say
  produces no diff — which is what makes the diff readable when there *is* something to
  say. That is also why nothing here is stamped with a time: a generated-at field would
  turn every refresh into a change, and dates are a non-goal besides.
* **It writes no new sentence.** Every character of content it emits already passed `add`
  — task lines are rendered verbatim, block titles come from the headings — so L4 holds and
  `lint` still proves the artefact. Column labels and totals are format, not prose.

That is also the boundary: a summary of a block, a release note, any text not already in a
validated line, is out of scope here and belongs to the author who calls `add`.

The README block is replaced **between two markers the author put there**. A missing marker
is refused with the two lines to paste, on the same reasoning as an undeclared block (RK37):
a write that invents its own container puts text where nothing looks for it.

A projection nothing writes is a chore with an exit code, so :func:`refreshes` is what every
governed write carries: the block is derived from the documents the transaction already
holds, inside the same `write_all` (RK188, RK187). `export` stays the command, for the tree
somebody hand-edited and for the first block a project ever renders.

Idempotence is what the gate over the block is made of (RK104), so it is a property to hold
rather than a claim to make, and two things here hold it. :func:`project` takes the governed
files as **documents** where it is asked to, which is how the same block can be derived at a
revision instead of from this working tree; and the next-ready line is picked *claim-blind*,
because a claim is dated in a temp file outside the repository and expires on a clock — so a
projection that read one would change bytes with no commit to explain it, and a gate over
those bytes would be red for a reason nobody could look up.
"""

from __future__ import annotations

import functools
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from html import escape
from pathlib import Path

from roadkeep.backlog import Backlog
from roadkeep.config import Config
from roadkeep.counting import Census
from roadkeep.kernel.document import Document, Entry, StaleFile, Write
from roadkeep.picking import pick

#: The container, as a comment so it renders as nothing in either file it lives in — the
#: same two lines in Markdown and in HTML, which is why one `splice` serves both.
BEGIN = "<!-- roadkeep:begin -->"
END = "<!-- roadkeep:end -->"

@dataclass(frozen=True, slots=True)
class Kind:
    """Where one flag writes when it names no path, and the shape the block takes there.

    A record since RK1110, where the pair stopped being two literals. The first two targets
    are files this tool does not own and names outright; the contents is *inside* a governed
    file, whose path is the project's own `[files]` declaration (L6) — so a target is either a
    name or a role, and which of the two decides where it lands.
    """

    shape: str
    #: The literal path, relative to the root, for a target outside the governed set.
    name: str = ""
    #: The governed role whose own file carries the block, for one inside it.
    role: str = ""


#: One statement of the pair, because the gate over the block (RK104) has to read exactly
#: what the write produces: a second spelling of `README.md` in the linter would be a gate
#: over a path nothing writes, which passes for the same reason the drift got in.
DEFAULTS: Mapping[str, Kind] = {
    "readme": Kind(shape="markdown", name="README.md"),
    "site": Kind(shape="html", name="docs/index.html"),
    # Improvements and not every prose role (RK1110): it is the file both live corpora keep a
    # contents in, and one flag per role is a decision to make when a project wants the second.
    "contents": Kind(shape="contents", role="improvements"),
}

#: The governed files a projection is derived from — the three whose unit is a task line.
#: The prose files hold no count and no next-ready line, so only the contents reads one.
COUNTED_ROLES = ("roadmap", "changelog", "deferred")

#: The prose role the contents is derived from, which is a *reading* of that file's headings
#: and never a count of its lines (RK1110).
LISTED_ROLE = "improvements"


def _note(command: str) -> str:
    return f"<!-- generated by `roadkeep export {command}`; edit the governed files instead -->"


class NoMarkers(ValueError):
    """The file has nowhere to put the projection, and a write may not invent one."""

    def __init__(self, where: str, missing: str) -> None:
        super().__init__(
            f"{where} has no {missing} marker: paste these two lines where the "
            f"projection belongs, then re-run —\n{BEGIN}\n{END}"
        )


class NoTarget(ValueError):
    """The file a named projection would be written into is not there at all (RK1039).

    One state earlier than :class:`NoMarkers`, and until this it was the one state this verb
    answered with an errno: `export --readme` on a project that has no README yet printed
    `[Errno 2] No such file or directory` and the **absolute** path, where every other message
    here prints the path relative to the root and names the command that closes it.

    The sentence was already written for the file next door — a README that exists and carries
    no markers is told to paste two lines — so this is that answer one step earlier, the file
    being what the caller creates rather than a flag they pass. A bare `--readme` reaches it
    too: the flag's `const` is the default path, so naming nothing still names a target, which
    is why the "not there is not a target" rule below could never cover this door.
    """

    def __init__(self, where: str) -> None:
        super().__init__(
            f"{where} is not there: a projection is written between two markers, so create "
            f"the file with these two lines where it belongs, then re-run —\n{BEGIN}\n{END}"
        )


@dataclass(frozen=True, slots=True)
class Row:
    """One block, counted in both files."""

    label: str
    title: str
    open: int
    shipped: int
    retired: int


@dataclass(frozen=True, slots=True)
class Listed:
    """One heading a contents lists, as the file already writes it (RK1110).

    Every field is read off the heading: the text a reader clicks, the fragment it lands on,
    and the depth that decides its indent. Nothing composed — which is what makes the contents
    a projection and not a second author (L4).
    """

    #: The heading's own text, less the `#`s: `§RK9 A design`, `VIII. The gateway`.
    heading: str
    #: The fragment the link points at, by the rule :func:`slug` states.
    slug: str
    level: int


#: The character categories a heading fragment drops, beyond the two it keeps (RK1110).
#: `Sm` is `+` and `↔`; `Sk` is the backtick a heading quotes a type name in. Both had to be
#: measured rather than assumed: with punctuation alone the rule reproduced 44 of 49 link
#: targets across Shio, Turing and claude-tray, and with these two it reproduces 47 — the
#: other two being links those files have already gone stale against, which is this task.
_DROPPED_CATEGORIES = frozenset({"Sm", "Sk"})


def slug(heading: str) -> str:
    """The fragment a Markdown renderer gives this heading, by the rule the corpora show.

    Lowercased, punctuation and the two symbol classes above removed, spaces to hyphens —
    with `-` and `_` kept, both being characters an author writes *into* a fragment. An emoji
    survives (`✅` is `So`), which is not a detail: Shio's contents links a heading carrying
    one, and a rule that stripped it would break fifteen live anchors at once.

    Held against the three corpora by `tests/test_exporting.py` rather than argued here: the
    renderer's algorithm is somebody else's, so the only honest check is whether this
    reproduces the fragments those files already link to.
    """
    import unicodedata  # noqa: PLC0415 - one call, on a path that runs per heading

    kept = "".join(
        character
        for character in heading.lower()
        if character in "-_"
        or not (
            unicodedata.category(character).startswith("P")
            or unicodedata.category(character) in _DROPPED_CATEGORIES
        )
    )
    return kept.replace(" ", "-")


@dataclass(frozen=True, slots=True)
class Projection:
    """The backlog as another file would restate it, in two shapes."""

    rows: tuple[Row, ...]
    open_entries: tuple[Entry, ...]
    ledger_entries: tuple[Entry, ...]
    next_ready: Entry | None
    files: dict[str, str]
    prefix: str
    #: True when any line was retired: a column of zeroes is noise, not information.
    show_retired: bool
    #: The prose file's own headings, for the contents block (RK1110). Empty where the project
    #: declares no such file or the caller gave a tree that did not carry it — and then the
    #: target is not written, exactly as an absent README is not one.
    listed: tuple[Listed, ...] = ()

    @property
    def totals(self) -> Row:
        return Row(
            label="",
            title="Total",
            open=sum(row.open for row in self.rows),
            shipped=sum(row.shipped for row in self.rows),
            retired=sum(row.retired for row in self.rows),
        )

    # -- the two shapes ----------------------------------------------------

    @property
    def progress(self) -> int:
        """Shipped as a whole percentage of everything counted, floored.

        Floored and not rounded, for the same reason the README carries no estimate: a bar
        that reads 100% with one line still open is the only wrong number a meter can show.
        """
        totals = self.totals
        counted = totals.open + totals.shipped + totals.retired
        return 0 if not counted else min(100, totals.shipped * 100 // counted)

    def body(self, shape: str, *, omit: str = "") -> str:
        """The block one target takes, addressed by the shape :data:`DEFAULTS` names it by.

        One door, because the write and the gate over it (RK104) have to render the same
        bytes: a caller that chose between the two methods itself would be a second place
        the pairing lives, and the linter is exactly the caller that must not get it wrong.

        ``omit`` is the heading the block is written *under* (RK1110), which only the contents
        has any use for: a list that links the section it is inside is a row nobody follows.
        Passed in rather than derived here, because where the markers sit is a fact about the
        file and both callers already hold that file's text — :func:`enclosing` reads it.
        """
        if shape == "html":
            return self.html()
        if shape == "markdown":
            return self.markdown()
        if shape == "contents":
            return self.contents(omit=omit)
        raise KeyError(f"no such projection shape: {shape!r}")

    def contents(self, *, omit: str = "") -> str:
        """The prose file's families, as the list that file already keeps by hand.

        **One level, and it is the corpus that says so.** Listing every heading was the first
        answer and it was wrong twice over: 55 rows against the 17 Shio keeps, and a reader
        handed every `###` design in a 900-line file has an index the size of the thing it
        indexes. Both live corpora list the families alone — Shio's 15 links and claude-tray's
        18 are all top-level — and a subsection is reached from the family it belongs to.

        So the depth is the shallowest heading *below the title*, whatever that file writes it
        as: `##` in both corpora, and derived rather than assumed because the level a project
        organises by is the project's (L6, without a key to declare it).

        Three headings are left out. The `#` names the file, and a contents linking the document
        it is inside is a row nobody follows; ``omit`` is the heading this block is written
        under, the same reason one step in; and anything deeper than the families belongs to
        one of them. What is *not* excluded is an unanchored heading (RK1107): the question a
        reader asks of a contents is what is in here, and a `## Table of contents` is as much
        in here as a numbered family.
        """
        below = [one for one in self.listed if one.level > 1]
        lines = [_note("--contents"), ""]
        if not below:
            return "\n".join(lines)
        family = min(one.level for one in below)
        for one in below:
            if one.level == family and one.heading != omit:
                lines.append(f"- [{one.heading}](#{one.slug})")
        return "\n".join(lines)

    def markdown(self) -> str:
        """The README block's body. Deterministic, and every line derived."""
        head = ["Block", "Open", "Shipped"] + (["Retired"] if self.show_retired else [])
        lines = [_note("--readme"), "", _row(head), _row(["---"] * len(head))]
        for row in self.rows:
            lines.append(_row(self._cells(row)))
        totals = self.totals
        lines.append(_row([f"**{totals.title}**", *self._cells(totals)[1:]]))
        if self.next_ready is not None:
            lines += ["", "**Next ready:**", "", self.next_ready.raw]
        return "\n".join(lines)

    def _cells(self, row: Row) -> list[str]:
        cells = [row.title, str(row.open), str(row.shipped)]
        return cells + ([str(row.retired)] if self.show_retired else [])

    def html(self) -> str:
        """The landing page's status block — the half of RK39 the JSON payload did not reach.

        A page is not a README with tags: it carries a meter and a per-block strip rather
        than a table, so this is a second *shape* and not a second *source*. Everything is
        still `escape`d and still verbatim, because a symptom holding an ``&`` would
        otherwise be a projection that emits broken markup from a line that validated.
        """
        totals = self.totals
        counted = totals.open + totals.shipped + totals.retired
        out = [
            _note("--site"),
            '<div class="status-bar reveal">',
            f'  <span class="lbl"><b>{totals.shipped}</b> of <b>{counted}</b> '
            f"tasks shipped</span>",
            f'  <div class="meter"><i style="width:{self.progress}%"></i></div>',
            "</div>",
            '<div class="blocks reveal">',
        ]
        for row in self.rows:
            state = "done" if not row.open else "open"
            # The count leads and the title follows: a block heading here is a whole
            # sentence with a parenthetical, and a card that puts it beside the number
            # squeezes both. The strip is read for the numbers.
            out += [
                f'  <div class="blk {state}">',
                f'    <span class="b-n">{row.shipped} shipped · {row.open} open</span>',
                f'    <span class="b-t">{escape(row.title)}</span>',
                "  </div>",
            ]
        out.append("</div>")
        if self.next_ready is not None:
            task = self.next_ready.task
            out += [
                '<p class="next reveal">',
                f'  <span class="k">Next ready</span> <code>{escape(task.id)}</code> '
                f"— {escape(task.symptom)}",
                "</p>",
            ]
        return "\n".join(out)

    def payload(self) -> dict[str, object]:
        """The site build's shape. No timestamp, for the reason in the module docstring."""
        return {
            "prefix": self.prefix,
            "files": self.files,
            "blocks": [
                {
                    "label": row.label,
                    "title": row.title,
                    "open": row.open,
                    "shipped": row.shipped,
                    "retired": row.retired,
                }
                for row in self.rows
            ],
            "totals": {
                "open": self.totals.open,
                "shipped": self.totals.shipped,
                "retired": self.totals.retired,
            },
            "open": [_task_json(entry) for entry in self.open_entries],
            "ledger": [_task_json(entry) for entry in self.ledger_entries],
            "next": None if self.next_ready is None else self.next_ready.task.id,
        }

    def json(self) -> str:
        return json.dumps(self.payload(), indent=2)


def project(
    config: Config, documents: Mapping[str, Document] | None = None
) -> Projection:
    """Read the governed files and derive both shapes. Pure: nothing is written.

    ``documents`` is the governed files as some *other* tree holds them, keyed by role — the
    seam `lint --baseline` needs (RK104), since a block derived from this working tree and
    compared against a README at a revision would report every ship since as a defect that
    revision already had. Given, it is authoritative: a role it omits is a file that tree did
    not carry, never one to fall back to disk for.
    """
    held = _from_disk(config) if documents is None else documents
    roadmap_document = held.get("roadmap")
    if roadmap_document is None:
        raise KeyError("there is no roadmap to project: nothing states what is open")
    ledger_document = held.get("changelog")
    roadmap = Census.of(config, "roadmap", roadmap_document)
    ledger = (
        None
        if ledger_document is None
        else Census.of(config, "changelog", ledger_document)
    )

    shipped_marker = config.schema.shipped_marker
    retired_marker = config.schema.retired_marker
    titles = _titles(config, held)
    labels = list(dict.fromkeys([*roadmap.blocks, *(ledger.blocks if ledger else ())]))
    rows = tuple(
        Row(
            label=label,
            title=titles.get(label, f"Block {label}"),
            # A label the ledger declares and the roadmap does not is a block whose work
            # is all shipped: zero open, not a refusal. `select` is right to refuse an
            # undeclared block when a caller *asked* for one (RK28); here the label came
            # from the files themselves, so the question is answered rather than rejected.
            open=len(roadmap.select(block=label).counted) if label in roadmap.blocks else 0,
            shipped=_count(ledger, label, shipped_marker),
            retired=_count(ledger, label, retired_marker),
        )
        for label in labels
    )
    choice = pick(
        config,
        backlog=Backlog.during(
            config,
            roadmap=roadmap_document,
            ledger=ledger_document,
            store=held.get("deferred"),
        ),
        claims=False,
    )
    return Projection(
        rows=rows,
        open_entries=roadmap.counted,
        ledger_entries=ledger.counted if ledger else (),
        next_ready=choice.entry,
        files={
            role: config.relative(config.path(role))
            for role in ("roadmap", "changelog", "improvements", "strategy")
            if config.has(role)
        },
        prefix=config.schema.prefix,
        show_retired=any(
            e.task.status == retired_marker for e in (ledger.counted if ledger else ())
        ),
        listed=_listed(held.get(LISTED_ROLE)),
    )


def _listed(document: Document | None) -> tuple[Listed, ...]:
    """Every heading of the prose file, in file order, as the contents lists them (RK1110).

    Off `Document.headings` and not off :func:`~roadkeep.sections.anchored`, which is the
    decision worth stating: `anchored` drops a heading that declares no address, and those are
    exactly the rows RK1107 made addressable and a reader still wants listed. A contents is
    about what the file contains, not about what carries a pointer.
    """
    if document is None:
        return ()
    return tuple(
        Listed(heading=text, slug=slug(text), level=heading.level)
        for heading in document.headings
        if (text := heading.text.strip())
    )


def refreshes(config: Config, held: Sequence[Document]) -> tuple[Write, ...]:
    """The projection writes a transaction owes for the files it is about to replace (RK188).

    Called with the *edited* documents, before any of them lands, so the block is derived
    from the state the transaction is creating and not from the one on disk — which is what
    makes this a refresh rather than a second pass. Roles the transaction does not hold are
    read from disk, because a projection counts three files and a `ship` writes at most two
    of them.

    Returns nothing where nothing changed, so an idempotent write stays idempotent: a
    `section amend` moves no count and no next-ready line, and the README's mtime should
    say so. The staleness question is asked here rather than in the caller for the reason
    :data:`DEFAULTS` exists — the gate reads exactly what the write produces, and a second
    place deciding "is it current" is a second answer to have wrong.
    """
    documents = dict(_from_disk(config))
    for document in held:
        role = _role_of(config, document.path)
        if role is not None:
            documents[role] = document
    if "roadmap" not in documents:
        return ()
    projection = project(config, documents)
    writes: list[Write] = []
    for flag in DEFAULTS:
        write, _ = splice_into(config, projection, flag)
        if write is not None:
            writes.append(write)
    return tuple(writes)


def _role_of(config: Config, path: Path | None) -> str | None:
    """Which projected role a file about to be written is, or None for one nothing projects.

    The prose role joined the three counted ones with RK1110: a `section drop` edits the file
    the contents lists, so a transaction holding it has to hand *that* version over — refreshing
    from disk would derive the contents from the headings the drop is in the middle of removing.
    """
    if path is None:
        return None
    for role in (*COUNTED_ROLES, LISTED_ROLE):
        if config.has(role) and config.path(role) == path:
            return role
    return None


def target_of(config: Config, flag: str) -> Path | None:
    """The file this flag writes when it names no path, or None where the project has none.

    One resolver for the write and for the gate (RK1110), which is :data:`DEFAULTS`' own reason
    for existing: a target is a literal name or a governed role, and a second place deciding
    which would be a gate reading a path nothing writes.
    """
    kind = DEFAULTS[flag]
    if kind.role:
        return config.path(kind.role) if config.has(kind.role) else None
    return config.root / kind.name


def splice_into(
    config: Config, projection: Projection, flag: str, name: str | None = None
) -> tuple[Write | None, str]:
    """Plan one target's marked block: the write to make, and which of two things happened.

    One planner for the command and for the refresh a governed write carries (RK188), so
    `export --readme` and a `ship` put the same bytes in the same place. ``name`` is the
    path the flag was given on the command line; without one the target is where
    :data:`DEFAULTS` says that flag writes, and a file that is not there is not a target —
    an adopting project has a README long before it has a block in one.
    """
    resolved = config.root / name if name is not None else target_of(config, flag)
    if resolved is None:
        # A role this project does not declare (RK1110): the same answer an absent file gets,
        # because a project with no rationale file has no contents to be stale.
        return None, f"no {DEFAULTS[flag].role} file is declared"
    target = resolved
    where = config.relative(target)
    if not target.is_file():
        # Silent where nothing named it — a `ship` refreshes whatever a project happens to
        # keep, and an adopting one has a README long before it has a block in it. Refused
        # where the flag did (RK1039), including the bare `--readme` whose `const` names the
        # default: a caller who asked for a projection is owed a sentence, not an errno.
        if name is None:
            return None, f"{where} is not there"
        raise NoTarget(where)
    with target.open("r", encoding="utf-8", newline="") as handle:
        before = handle.read()
    if name is None and BEGIN not in before:
        # The markers are the declaration (RK37), the same reading the gate makes: a file
        # carrying none is not a target, so a refresh never opens a container an author
        # did not ask for. Named on the command line, the missing marker is still refused.
        return None, f"{where} carries no projection"
    after = splice(
        before, projection.body(DEFAULTS[flag].shape, omit=enclosing(before)), where
    )
    if after == before:
        # The point of idempotence, said out loud: nothing changed, so nothing is written
        # and the file's mtime does not move either.
        return None, f"{where} is already current"
    return (
        Write(target, after, functools.partial(_assert_unmoved, target, before)),
        f"{where} refreshed between the roadkeep markers",
    )


def _assert_unmoved(target: Path, before: str) -> None:
    """The question `Document.save` asks (RK116), on the one file with no document (RK132).

    Every governed write goes through `save` and is refused if the target stopped being the
    file that was read. This one splices text into a README, which this tool does not own
    and would be claiming a format it does not have by parsing — so the check is the same
    question asked by hand: the bytes that were read, compared before the rename. A README
    is the file most likely to be open in an editor while a command runs, which is exactly
    the writer a lock does not order, and `--site` is the same splice on a second file.
    """
    if not target.is_file():
        raise StaleFile(target, missing=True)
    with target.open("r", encoding="utf-8", newline="") as handle:
        if handle.read() != before:
            raise StaleFile(target)


def splice(text: str, body: str, where: str) -> str:
    """Replace what is between the markers, and nothing else.

    Everything outside them is kept byte for byte, including the file's line endings: the
    author owns that text and a projection that reformatted it would be an editor.
    """
    newline = "\r\n" if "\r\n" in text else "\n"
    lines = text.split(newline)
    begin = _index(lines, BEGIN, where, "begin")
    end = _index(lines, END, where, "end")
    if end < begin:
        raise NoMarkers(where, "correctly ordered begin/end")
    replaced = [*lines[: begin + 1], *body.split("\n"), *lines[end:]]
    return newline.join(replaced)


def enclosing(text: str) -> str:
    """The heading the roadkeep block is written under, less its `#`s (RK1110).

    One reader for the write and for the gate, because both hold the target's text and the
    contents needs to know which of the headings it lists is the one it is inside. Empty where
    the block is above every heading or there is no marker at all — a projection at the top of
    a file lists nothing twice, so there is nothing to leave out.
    """
    found = ""
    for line in text.split("\n"):
        if line.startswith("#"):
            found = line.lstrip("#").strip()
        elif line.strip() == BEGIN:
            return found
    return ""


def _index(lines: list[str], marker: str, where: str, name: str) -> int:
    for number, line in enumerate(lines):
        if line.strip() == marker:
            return number
    raise NoMarkers(where, name)


def _from_disk(config: Config) -> dict[str, Document]:
    """The projected roles this project declares and has, each under its own schema.

    Four since RK1110: the three counted, plus the prose file the contents lists. Read here
    rather than in the renderer for the reason every other role is — `project` takes documents
    so a baseline can hand it a revision's, and a role that fell back to disk on its own would
    be the one input a `--baseline` run could not replace.
    """
    return {
        role: config.document(role)
        for role in (*COUNTED_ROLES, LISTED_ROLE)
        if config.has(role) and config.path(role).is_file()
    }


def _titles(config: Config, held: Mapping[str, Document]) -> dict[str, str]:
    """Block titles from the headings that declare them, roadmap first, verbatim."""
    out: dict[str, str] = {}
    for role in ("changelog", "roadmap"):  # the roadmap is read last, so its wording wins
        document = held.get(role)
        if document is None:
            continue
        for heading in document.headings:
            if heading.label:
                out[heading.label] = heading.text.removeprefix(
                    f"{config.schema.heading_word} "
                )
    return out


def _count(ledger: Census | None, label: str, marker: str) -> int:
    if ledger is None:
        return 0
    return sum(
        1
        for entry in ledger.counted
        if entry.task.block == label and entry.task.status == marker
    )


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(_cell(text) for text in cells) + " |"


def _cell(text: str) -> str:
    """One cell, escaped as :func:`html.escape` escapes the other shape's (RK487).

    A block title is the heading's own words, and a bar in one is the separator this row is
    built from — so the cell splits, every count after it shifts a column, and the totals row
    below stays right, which is a projection contradicting itself about work nobody changed.

    Here rather than in :meth:`Projection._cells` for the reason :data:`DEFAULTS` is one
    mapping: the linter re-derives this block and compares bytes (RK104), so a second place
    deciding what a cell looks like is a second answer to have wrong. Head, separator, data
    and totals all arrive through this door.

    The backslash goes first, because `\\|` is what GFM reads as a literal bar — escaping the
    bar alone would turn a title that already carried a backslash into one whose escape the
    author never wrote.
    """
    return text.replace("\\", "\\\\").replace("|", "\\|")


def _task_json(entry: Entry) -> dict[str, object]:
    task = entry.task
    return {
        "id": task.id,
        "status": task.status,
        "block": task.block,
        "symptom": task.symptom,
        "why": task.why,
        "deps": [dep.render() for dep in task.deps],
        "ref": task.ref,
        "line": entry.lineno,
    }
