"""A projection of the backlog, never a second author (RK39).

A README section and a site page repeat what the backlog says and drift the moment it
changes, because nothing re-derives them. This repository's own README claimed **8 of 36
tasks shipped** and listed `add`, `ship`, `pick` and `show` as "not yet built" while all
four were in the ledger — written by the same session that shipped them.

So the restatement is derived. Two properties make it a projection rather than a generator:

* **Idempotent.** The same `docs/` yields the same bytes, so a refresh with nothing to say
  produces no diff — which is what makes the diff readable when there *is* something to
  say. That is also why nothing here is stamped with a time: a generated-at field would
  turn every refresh into a change, and dates are a non-goal besides.
* **It writes no new sentence.** Every character of content it emits already passed `add`
  — task lines are rendered verbatim, block titles come from the headings — so L4 holds and
  `lint` still proves the artefact. Column labels and totals are format, not prose.

That is also the boundary: a summary of a block, a release note, any text not already in a
validated line, is out of scope here and belongs to the author who calls `add`.

The README block is replaced **between two markers the author put there**. A missing marker
is refused with the two lines to paste, on the same reasoning as an undeclared block (RK37):
a write that invents its own container puts text where nothing looks for it.

Idempotence is what the gate over the block is made of (RK104), so it is a property to hold
rather than a claim to make, and two things here hold it. :func:`project` takes the governed
files as **documents** where it is asked to, which is how the same block can be derived at a
revision instead of from this working tree; and the next-ready line is picked *claim-blind*,
because a claim is dated in a temp file outside the repository and expires on a clock — so a
projection that read one would change bytes with no commit to explain it, and a gate over
those bytes would be red for a reason nobody could look up.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from html import escape

from roadkeep.backlog import Backlog
from roadkeep.config import Config
from roadkeep.counting import Census
from roadkeep.document import Document, Entry
from roadkeep.picking import pick

#: The container, as a comment so it renders as nothing in either file it lives in — the
#: same two lines in Markdown and in HTML, which is why one `splice` serves both.
BEGIN = "<!-- roadkeep:begin -->"
END = "<!-- roadkeep:end -->"

#: Which file each flag writes when it names no path, and the shape the block takes there.
#: One statement of the pair, because the gate over the block (RK104) has to read exactly
#: what the write produces: a second spelling of `README.md` in the linter would be a gate
#: over a path nothing writes, which passes for the same reason the drift got in.
DEFAULTS: Mapping[str, tuple[str, str]] = {
    "readme": ("README.md", "markdown"),
    "site": ("docs/index.html", "html"),
}

#: The governed files a projection is derived from — the three whose unit is a task line.
#: The prose files hold no count and no next-ready line, so nothing here reads them.
COUNTED_ROLES = ("roadmap", "changelog", "deferred")


def _note(command: str) -> str:
    return f"<!-- generated by `roadkeep export {command}`; edit the governed files instead -->"


class NoMarkers(ValueError):
    """The file has nowhere to put the projection, and a write may not invent one."""

    def __init__(self, where: str, missing: str) -> None:
        super().__init__(
            f"{where} has no {missing} marker: paste these two lines where the "
            f"projection belongs, then re-run —\n{BEGIN}\n{END}"
        )


@dataclass(frozen=True, slots=True)
class Row:
    """One block, counted in both files."""

    label: str
    title: str
    open: int
    shipped: int
    retired: int


@dataclass(frozen=True, slots=True)
class Projection:
    """The backlog as another file would restate it, in two shapes."""

    rows: tuple[Row, ...]
    open_entries: tuple[Entry, ...]
    ledger_entries: tuple[Entry, ...]
    next_ready: Entry | None
    files: dict[str, str]
    prefix: str
    #: True when any line was retired: a column of zeroes is noise, not information.
    show_retired: bool

    @property
    def totals(self) -> Row:
        return Row(
            label="",
            title="Total",
            open=sum(row.open for row in self.rows),
            shipped=sum(row.shipped for row in self.rows),
            retired=sum(row.retired for row in self.rows),
        )

    # -- the two shapes ----------------------------------------------------

    @property
    def progress(self) -> int:
        """Shipped as a whole percentage of everything counted, floored.

        Floored and not rounded, for the same reason the README carries no estimate: a bar
        that reads 100% with one line still open is the only wrong number a meter can show.
        """
        totals = self.totals
        counted = totals.open + totals.shipped + totals.retired
        return 0 if not counted else min(100, totals.shipped * 100 // counted)

    def body(self, shape: str) -> str:
        """The block one target takes, addressed by the shape :data:`DEFAULTS` names it by.

        One door, because the write and the gate over it (RK104) have to render the same
        bytes: a caller that chose between the two methods itself would be a second place
        the pairing lives, and the linter is exactly the caller that must not get it wrong.
        """
        if shape == "html":
            return self.html()
        if shape == "markdown":
            return self.markdown()
        raise KeyError(f"no such projection shape: {shape!r}")

    def markdown(self) -> str:
        """The README block's body. Deterministic, and every line derived."""
        head = ["Block", "Open", "Shipped"] + (["Retired"] if self.show_retired else [])
        lines = [_note("--readme"), "", _row(head), _row(["---"] * len(head))]
        for row in self.rows:
            lines.append(_row(self._cells(row)))
        totals = self.totals
        lines.append(_row([f"**{totals.title}**", *self._cells(totals)[1:]]))
        if self.next_ready is not None:
            lines += ["", "**Next ready:**", "", self.next_ready.raw]
        return "\n".join(lines)

    def _cells(self, row: Row) -> list[str]:
        cells = [row.title, str(row.open), str(row.shipped)]
        return cells + ([str(row.retired)] if self.show_retired else [])

    def html(self) -> str:
        """The landing page's status block — the half of RK39 the JSON payload did not reach.

        A page is not a README with tags: it carries a meter and a per-block strip rather
        than a table, so this is a second *shape* and not a second *source*. Everything is
        still `escape`d and still verbatim, because a symptom holding an ``&`` would
        otherwise be a projection that emits broken markup from a line that validated.
        """
        totals = self.totals
        counted = totals.open + totals.shipped + totals.retired
        out = [
            _note("--site"),
            '<div class="status-bar reveal">',
            f'  <span class="lbl"><b>{totals.shipped}</b> of <b>{counted}</b> '
            f"tasks shipped</span>",
            f'  <div class="meter"><i style="width:{self.progress}%"></i></div>',
            "</div>",
            '<div class="blocks reveal">',
        ]
        for row in self.rows:
            state = "done" if not row.open else "open"
            # The count leads and the title follows: a block heading here is a whole
            # sentence with a parenthetical, and a card that puts it beside the number
            # squeezes both. The strip is read for the numbers.
            out += [
                f'  <div class="blk {state}">',
                f'    <span class="b-n">{row.shipped} shipped · {row.open} open</span>',
                f'    <span class="b-t">{escape(row.title)}</span>',
                "  </div>",
            ]
        out.append("</div>")
        if self.next_ready is not None:
            task = self.next_ready.task
            out += [
                '<p class="next reveal">',
                f'  <span class="k">Next ready</span> <code>{escape(task.id)}</code> '
                f"— {escape(task.symptom)}",
                "</p>",
            ]
        return "\n".join(out)

    def payload(self) -> dict[str, object]:
        """The site build's shape. No timestamp, for the reason in the module docstring."""
        return {
            "prefix": self.prefix,
            "files": self.files,
            "blocks": [
                {
                    "label": row.label,
                    "title": row.title,
                    "open": row.open,
                    "shipped": row.shipped,
                    "retired": row.retired,
                }
                for row in self.rows
            ],
            "totals": {
                "open": self.totals.open,
                "shipped": self.totals.shipped,
                "retired": self.totals.retired,
            },
            "open": [_task_json(entry) for entry in self.open_entries],
            "ledger": [_task_json(entry) for entry in self.ledger_entries],
            "next": None if self.next_ready is None else self.next_ready.task.id,
        }

    def json(self) -> str:
        return json.dumps(self.payload(), indent=2)


def project(
    config: Config, documents: Mapping[str, Document] | None = None
) -> Projection:
    """Read the governed files and derive both shapes. Pure: nothing is written.

    ``documents`` is the governed files as some *other* tree holds them, keyed by role — the
    seam `lint --baseline` needs (RK104), since a block derived from this working tree and
    compared against a README at a revision would report every ship since as a defect that
    revision already had. Given, it is authoritative: a role it omits is a file that tree did
    not carry, never one to fall back to disk for.
    """
    held = _from_disk(config) if documents is None else documents
    roadmap_document = held.get("roadmap")
    if roadmap_document is None:
        raise KeyError("there is no roadmap to project: nothing states what is open")
    ledger_document = held.get("changelog")
    roadmap = Census.of(config, "roadmap", roadmap_document)
    ledger = (
        None
        if ledger_document is None
        else Census.of(config, "changelog", ledger_document)
    )

    shipped_marker = config.schema.shipped_marker
    retired_marker = config.schema.retired_marker
    titles = _titles(config, held)
    labels = list(dict.fromkeys([*roadmap.blocks, *(ledger.blocks if ledger else ())]))
    rows = tuple(
        Row(
            label=label,
            title=titles.get(label, f"Block {label}"),
            open=len(roadmap.select(block=label).counted),
            shipped=_count(ledger, label, shipped_marker),
            retired=_count(ledger, label, retired_marker),
        )
        for label in labels
    )
    choice = pick(
        config,
        backlog=Backlog.during(
            config,
            roadmap=roadmap_document,
            ledger=ledger_document,
            store=held.get("deferred"),
        ),
        claims=False,
    )
    return Projection(
        rows=rows,
        open_entries=roadmap.counted,
        ledger_entries=ledger.counted if ledger else (),
        next_ready=choice.entry,
        files={
            role: config.relative(config.path(role))
            for role in ("roadmap", "changelog", "improvements", "strategy")
            if config.has(role)
        },
        prefix=config.schema.prefix,
        show_retired=any(
            e.task.status == retired_marker for e in (ledger.counted if ledger else ())
        ),
    )


def splice(text: str, body: str, where: str) -> str:
    """Replace what is between the markers, and nothing else.

    Everything outside them is kept byte for byte, including the file's line endings: the
    author owns that text and a projection that reformatted it would be an editor.
    """
    newline = "\r\n" if "\r\n" in text else "\n"
    lines = text.split(newline)
    begin = _index(lines, BEGIN, where, "begin")
    end = _index(lines, END, where, "end")
    if end < begin:
        raise NoMarkers(where, "correctly ordered begin/end")
    replaced = [*lines[: begin + 1], *body.split("\n"), *lines[end:]]
    return newline.join(replaced)


def _index(lines: list[str], marker: str, where: str, name: str) -> int:
    for number, line in enumerate(lines):
        if line.strip() == marker:
            return number
    raise NoMarkers(where, name)


def _from_disk(config: Config) -> dict[str, Document]:
    """The counted roles this project declares and has, each under its own schema."""
    return {
        role: config.document(role)
        for role in COUNTED_ROLES
        if config.has(role) and config.path(role).is_file()
    }


def _titles(config: Config, held: Mapping[str, Document]) -> dict[str, str]:
    """Block titles from the headings that declare them, roadmap first, verbatim."""
    out: dict[str, str] = {}
    for role in ("changelog", "roadmap"):  # the roadmap is read last, so its wording wins
        document = held.get(role)
        if document is None:
            continue
        for heading in document.headings:
            if heading.label:
                out[heading.label] = heading.text.removeprefix(
                    f"{config.schema.heading_word} "
                )
    return out


def _count(ledger: Census | None, label: str, marker: str) -> int:
    if ledger is None:
        return 0
    return sum(
        1
        for entry in ledger.counted
        if entry.task.block == label and entry.task.status == marker
    )


def _row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def _task_json(entry: Entry) -> dict[str, object]:
    task = entry.task
    return {
        "id": task.id,
        "status": task.status,
        "block": task.block,
        "symptom": task.symptom,
        "why": task.why,
        "deps": [dep.render() for dep in task.deps],
        "ref": task.ref,
        "line": entry.lineno,
    }
